#include "linux.h"
#include "minigamepad.h"
#include <linux/input-event-codes.h>

mg_gamepad_btn get_gamepad_btn(int btn) {
  switch (btn) {
  case BTN_0:
    return MG_GAMEPAD_BUTTON_0;
  case BTN_1:
    return MG_GAMEPAD_BUTTON_1;
  case BTN_2:
    return MG_GAMEPAD_BUTTON_2;
  case BTN_3:
    return MG_GAMEPAD_BUTTON_3;
  case BTN_4:
    return MG_GAMEPAD_BUTTON_4;
  case BTN_5:
    return MG_GAMEPAD_BUTTON_5;
  case BTN_6:
    return MG_GAMEPAD_BUTTON_6;
  case BTN_7:
    return MG_GAMEPAD_BUTTON_7;
  case BTN_8:
    return MG_GAMEPAD_BUTTON_8;
  case BTN_9:
    return MG_GAMEPAD_BUTTON_9;
  case BTN_SOUTH:
    return MG_GAMEPAD_BUTTON_10;
  case BTN_NORTH:
    return MG_GAMEPAD_BUTTON_11;
  case BTN_WEST:
    return MG_GAMEPAD_BUTTON_12;
  case BTN_EAST:
    return MG_GAMEPAD_BUTTON_13;
  case BTN_JOYSTICK:
    return MG_GAMEPAD_BUTTON_JOYSTICK;
  case BTN_THUMB:
    return MG_GAMEPAD_BUTTON_THUMB;
  case BTN_THUMB2:
    return MG_GAMEPAD_BUTTON_THUMB2;
  case BTN_TOP:
    return MG_GAMEPAD_BUTTON_TOP;
  case BTN_TOP2:
    return MG_GAMEPAD_BUTTON_TOP2;
  case BTN_PINKIE:
    return MG_GAMEPAD_BUTTON_PINKIE;
  case BTN_BASE:
    return MG_GAMEPAD_BUTTON_BASE;
  case BTN_BASE2:
    return MG_GAMEPAD_BUTTON_BASE2;
  case BTN_BASE3:
    return MG_GAMEPAD_BUTTON_BASE3;
  case BTN_BASE4:
    return MG_GAMEPAD_BUTTON_BASE4;
  case BTN_BASE5:
    return MG_GAMEPAD_BUTTON_BASE5;
  case BTN_BASE6:
    return MG_GAMEPAD_BUTTON_BASE6;
  case BTN_DEAD:
    return MG_GAMEPAD_BUTTON_DEAD;
  case BTN_C:
    return MG_GAMEPAD_BUTTON_C;
  case BTN_Z:
    return MG_GAMEPAD_BUTTON_Z;
  case BTN_TL:
    return MG_GAMEPAD_BUTTON_TL;
  case BTN_TR:
    return MG_GAMEPAD_BUTTON_TR;
  case BTN_TL2:
    return MG_GAMEPAD_BUTTON_TL2;
  case BTN_TR2:
    return MG_GAMEPAD_BUTTON_TR2;
  case BTN_SELECT:
    return MG_GAMEPAD_BUTTON_SELECT;
  case BTN_START:
    return MG_GAMEPAD_BUTTON_START;
  case BTN_MODE:
    return MG_GAMEPAD_BUTTON_MODE;
  case BTN_THUMBL:
    return MG_GAMEPAD_BUTTON_THUMBL;
  case BTN_THUMBR:
    return MG_GAMEPAD_BUTTON_THUMBR;
  case BTN_DIGI:
    return MG_GAMEPAD_BUTTON_DIGI;
  default:
    return MG_GAMEPAD_BUTTON_UNKNOWN;
  }
}

int get_native_btn(mg_gamepad_btn btn) {
  switch (btn) {
  case MG_GAMEPAD_BUTTON_0:
    return BTN_0;
  case MG_GAMEPAD_BUTTON_1:
    return BTN_1;
  case MG_GAMEPAD_BUTTON_2:
    return BTN_2;
  case MG_GAMEPAD_BUTTON_3:
    return BTN_3;
  case MG_GAMEPAD_BUTTON_4:
    return BTN_4;
  case MG_GAMEPAD_BUTTON_5:
    return BTN_5;
  case MG_GAMEPAD_BUTTON_6:
    return BTN_6;
  case MG_GAMEPAD_BUTTON_7:
    return BTN_7;
  case MG_GAMEPAD_BUTTON_8:
    return BTN_8;
  case MG_GAMEPAD_BUTTON_9:
    return BTN_9;
  case MG_GAMEPAD_BUTTON_JOYSTICK:
    return BTN_JOYSTICK;
  case MG_GAMEPAD_BUTTON_THUMB:
    return BTN_THUMB;
  case MG_GAMEPAD_BUTTON_THUMB2:
    return BTN_THUMB2;
  case MG_GAMEPAD_BUTTON_TOP:
    return BTN_TOP;
  case MG_GAMEPAD_BUTTON_TOP2:
    return BTN_TOP2;
  case MG_GAMEPAD_BUTTON_PINKIE:
    return BTN_PINKIE;
  case MG_GAMEPAD_BUTTON_BASE:
    return BTN_BASE;
  case MG_GAMEPAD_BUTTON_BASE2:
    return BTN_BASE2;
  case MG_GAMEPAD_BUTTON_BASE3:
    return BTN_BASE3;
  case MG_GAMEPAD_BUTTON_BASE4:
    return BTN_BASE4;
  case MG_GAMEPAD_BUTTON_BASE5:
    return BTN_BASE5;
  case MG_GAMEPAD_BUTTON_BASE6:
    return BTN_BASE6;
  case MG_GAMEPAD_BUTTON_DEAD:
    return BTN_DEAD;
  case MG_GAMEPAD_BUTTON_10:
    return BTN_SOUTH;
  case MG_GAMEPAD_BUTTON_13:
    return BTN_EAST;
  case MG_GAMEPAD_BUTTON_C:
    return BTN_C;
  case MG_GAMEPAD_BUTTON_11:
    return BTN_NORTH;
  case MG_GAMEPAD_BUTTON_12:
    return BTN_WEST;
  case MG_GAMEPAD_BUTTON_Z:
    return BTN_Z;
  case MG_GAMEPAD_BUTTON_TL:
    return BTN_TL;
  case MG_GAMEPAD_BUTTON_TR:
    return BTN_TR;
  case MG_GAMEPAD_BUTTON_TL2:
    return BTN_TL2;
  case MG_GAMEPAD_BUTTON_TR2:
    return BTN_TR2;
  case MG_GAMEPAD_BUTTON_SELECT:
    return BTN_SELECT;
  case MG_GAMEPAD_BUTTON_START:
    return BTN_START;
  case MG_GAMEPAD_BUTTON_MODE:
    return BTN_MODE;
  case MG_GAMEPAD_BUTTON_THUMBL:
    return BTN_THUMBL;
  case MG_GAMEPAD_BUTTON_THUMBR:
    return BTN_THUMBR;
  case MG_GAMEPAD_BUTTON_DIGI:
    return BTN_DIGI;
  case MG_GAMEPAD_BUTTON_UNKNOWN:
    return BTN_MISC;
  }
};

mg_gamepad_axis get_gamepad_axis(int axis) {
  switch (axis) {
  case ABS_X:
    return MG_GAMEPAD_AXIS_X;
  case ABS_Y:
    return MG_GAMEPAD_AXIS_Y;
  case ABS_Z:
    return MG_GAMEPAD_AXIS_Z;
  case ABS_RX:
    return MG_GAMEPAD_AXIS_RX;
  case ABS_RY:
    return MG_GAMEPAD_AXIS_RY;
  case ABS_RZ:
    return MG_GAMEPAD_AXIS_RZ;
  case ABS_THROTTLE:
    return MG_GAMEPAD_AXIS_THROTTLE;
  case ABS_RUDDER:
    return MG_GAMEPAD_AXIS_RUDDER;
  case ABS_WHEEL:
    return MG_GAMEPAD_AXIS_WHEEL;
  case ABS_GAS:
    return MG_GAMEPAD_AXIS_GAS;
  case ABS_BRAKE:
    return MG_GAMEPAD_AXIS_BRAKE;
  case ABS_HAT0X:
    return MG_GAMEPAD_AXIS_HAT0X;
  case ABS_HAT0Y:
    return MG_GAMEPAD_AXIS_HAT0Y;
  case ABS_HAT1X:
    return MG_GAMEPAD_AXIS_HAT1X;
  case ABS_HAT1Y:
    return MG_GAMEPAD_AXIS_HAT1Y;
  case ABS_HAT2X:
    return MG_GAMEPAD_AXIS_HAT2X;
  case ABS_HAT2Y:
    return MG_GAMEPAD_AXIS_HAT2Y;
  case ABS_HAT3X:
    return MG_GAMEPAD_AXIS_HAT3X;
  case ABS_HAT3Y:
    return MG_GAMEPAD_AXIS_HAT3Y;
  case ABS_PRESSURE:
    return MG_GAMEPAD_AXIS_PRESSURE;
  case ABS_DISTANCE:
    return MG_GAMEPAD_AXIS_DISTANCE;
  case ABS_TILT_X:
    return MG_GAMEPAD_AXIS_TILT_X;
  case ABS_TILT_Y:
    return MG_GAMEPAD_AXIS_TILT_Y;
  case ABS_TOOL_WIDTH:
    return MG_GAMEPAD_AXIS_TOOL_WIDTH;
  case ABS_VOLUME:
    return MG_GAMEPAD_AXIS_VOLUME;
  case ABS_PROFILE:
    return MG_GAMEPAD_AXIS_PROFILE;
  case ABS_MISC:
    return MG_GAMEPAD_AXIS_MISC;
  default:
    return MG_GAMEPAD_AXIS_UNKNOWN;
  }
}

int get_native_axis(mg_gamepad_axis axis) {
  switch (axis) {
  case MG_GAMEPAD_AXIS_X:
    return ABS_X;
  case MG_GAMEPAD_AXIS_Y:
    return ABS_Y;
  case MG_GAMEPAD_AXIS_Z:
    return ABS_Z;
  case MG_GAMEPAD_AXIS_RX:
    return ABS_RX;
  case MG_GAMEPAD_AXIS_RY:
    return ABS_RY;
  case MG_GAMEPAD_AXIS_RZ:
    return ABS_RZ;
  case MG_GAMEPAD_AXIS_THROTTLE:
    return ABS_THROTTLE;
  case MG_GAMEPAD_AXIS_RUDDER:
    return ABS_RUDDER;
  case MG_GAMEPAD_AXIS_WHEEL:
    return ABS_WHEEL;
  case MG_GAMEPAD_AXIS_GAS:
    return ABS_GAS;
  case MG_GAMEPAD_AXIS_BRAKE:
    return ABS_BRAKE;
  case MG_GAMEPAD_AXIS_HAT0X:
    return ABS_HAT0X;
  case MG_GAMEPAD_AXIS_HAT0Y:
    return ABS_HAT0Y;
  case MG_GAMEPAD_AXIS_HAT1X:
    return ABS_HAT1X;
  case MG_GAMEPAD_AXIS_HAT1Y:
    return ABS_HAT1Y;
  case MG_GAMEPAD_AXIS_HAT2X:
    return ABS_HAT2X;
  case MG_GAMEPAD_AXIS_HAT2Y:
    return ABS_HAT2Y;
  case MG_GAMEPAD_AXIS_HAT3X:
    return ABS_HAT3X;
  case MG_GAMEPAD_AXIS_HAT3Y:
    return ABS_HAT3Y;
  case MG_GAMEPAD_AXIS_PRESSURE:
    return ABS_PRESSURE;
  case MG_GAMEPAD_AXIS_DISTANCE:
    return ABS_DISTANCE;
  case MG_GAMEPAD_AXIS_TILT_X:
    return ABS_TILT_X;
  case MG_GAMEPAD_AXIS_TILT_Y:
    return ABS_TILT_Y;
  case MG_GAMEPAD_AXIS_TOOL_WIDTH:
    return ABS_TOOL_WIDTH;
  case MG_GAMEPAD_AXIS_VOLUME:
    return ABS_VOLUME;
  case MG_GAMEPAD_AXIS_PROFILE:
    return ABS_PROFILE;
  default:
    return ABS_MISC;
  }
}