name: Build WebAssembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.52
      
    - name: Compile to WebAssembly
      run: |
        make
